namespace CityAppREST.Models
{
    public enum Categories
    {
        All,
        Accounting,
        Vliegveld,
        Aquarium,
        ATM,
        Bank,
        Bakkerij,
        Bar,
        BoekenWinkel,
        Bowling,
        Casino,
        CarWash,
        Tandarts,
        Brandweer,
        Fitness,
        Winkel,
        Zoo,
        Café,
        School,
        Restaurant,
        Park,
        Moskee,
        Juweelier,
        Wasserij
    }
}
